{% set name = "rlp" %}
{% set version = "4.1.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: be07564270a96f3e225e2c107db263de96b5bc1f27722d2855bd3459a08e95a9

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - setuptools
    - pip
    - python {{ python_min }}
    - setuptools-markdown
  run:
    - eth-utils >=2.0.0
    - python >={{ python_min }}

test:
  imports:
    - rlp
    - rlp.sedes
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/ethereum/pyrlp
  summary: A package for Recursive Length Prefix encoding and decoding
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - step21
